### ISSUE TITLE
some demos

### ISSUE THREAD

**Issue by ghost** [C-Chads/tinygl#19]
Thanks for your improvements to tinygl.

I make a android demo here : https://github.com/c0i/tinygl.android.
And use premake5 to generate visual studio project: https://github.com/c0i/TinyGL.ex

**Comment by gek169** [comment]
Wow! Cool!

**Comment by briancullinan** [comment]
Anybody tried this with webGL?

**Comment by gek169** [comment]
I haven't

**Comment by gek169** [comment]
(have I mentioned this is awesome stuff?)
