### ISSUE TITLE
Provide a viable demo like stm32 running on a microcontroller

### ISSUE THREAD

**Issue by fireflylr** [C-Chads/tinygl#22]
I see the author mention the possibility of running on embedded systems, but my level is limited and I don't know if I can provide a demo that runs on embedded .
Thank you!

**Comment by gek169** [comment]
I have actually ported it to the Nintendo 3DS, but that version is outdated and I think I deleted the post since it was so poorly done.
I would need to re-setup my Nintendo 3DS development environment to get that working again.

I will remember this
