### ISSUE TITLE
Compatibility questions.

### ISSUE THREAD

**Issue by XanCraft21** [C-Chads/tinygl#23]
Hello, i know this is not the best place to ask a question about compatibility, but i can’t find anywhere else to ask this.

i was wondering how flexible this library is with compatibility. Like, what languages will this work on (especially the outdated c++11), what platforms can this work on ( and if i can use Arduino IDE with strong processors), and what is the likelihood of this software running properly on older (or newer but slower) machines running outdated software versions.

if anyone is able to answer these questions, i will gladly appreciate it. Thank you for your help.

**Comment by gek169** [comment]
I maintain this library for C99 on 32 bit systems or higher.

**Comment by XanCraft21** [comment]
Ok. Will this work on compilers than run an old version of c++ like c++11?

**Comment by goshhhy** [comment]
this is not a C++ library, this is a C library. it is maintained for C99 - the 1999 version of C.

it will work with C99 compilers, and may work with C++ compilers that include C99 support.

**Comment by XanCraft21** [comment]
Ok, thanks for the help.

**Comment by gek169** [comment]
if you're using gcc, Compile under std=gnu99 and link using the same compiler with g++
