### ISSUE TITLE
Texture perspective correction is broken. Texture still warps even when enabled.

### ISSUE THREAD

**Issue by XanCraft21** [C-Chads/tinygl#27]
Hello, i have found a bug that involves texture perspective correction. I enabled it with glHint and i’m still seeing texture warping.

I was talking to one of the contributors on Discord, he said it will be hard to fix, then he never got back with me. I hope everything is ok.

Am I forgetting any extra steps that must be done before the perspective correction hint, or is there a hidden bug somewhere? If anyone knows i will gladly appreciate the help. Thank you.

**Comment by XanCraft21** [comment]
Please disregard this issue, i got the texture correction to work. I just added a projection matrix and some camera coordinates. I never thought i needed to add a projection matrix.

I want to keep this open so i can ask for help questions on this topic. Thank you for your help.

**Comment by gek169** [comment]
... Alright! i'll leave the issue open, then.

**Comment by gek169** [comment]
Errrr?
