### ISSUE TITLE
CMake build?

### ISSUE THREAD

**Issue by starseeker** [C-Chads/tinygl#4]
Hi!  Last year I was looking into tinygl a bit, but I didn't get nearly as far as you have with repairing it - nice work!

Would you be interested in a CMake build for this library?  I've found it makes it easier to test on things like Windows, and it probably wouldn't be too hard to adjust my setup for your tinygl, but I thought I'd check first and see if that's something that might be of interest to you before preparing a pull request.

Cheers,
CY

**Comment by gek169** [comment]
It would be interesting...
As long as it doesn't mess up the existing `make` i'm 100% interested in it. Make a PR!

If you would like to know about the changes and how you could go about implementing it in your own project, I can provide assistance. I tried to retain Bellard's original code organization, but I improved it slightly and I removed the BeOS/X11 bindings.

Thanks for posting!

**Comment by starseeker** [comment]
I see you do already have a toplevel CMakeLists.txt file (apologies, I didn't catch that right away - I was focused on the Makefiles and excited by seeing correct rendering with the gears demo so I missed it initially).   Given that, my pull request will amount to proposing some changes that are sort of "CMake recommended practice", like explicit file listing in lieu of globbing and adding some install rules for the libs and headers.  (No worries if you prefer to stick with your current style - I just figure I should send them back upstream in case they're of interest.)

My potential application for this, although I'm not 100% sure yet how practical it is, is to use tinygl as a software rendering fallback for the BRL-CAD open source CAD system:  https://github.com/BRL-CAD/brlcad

We have a REALLY long history, and our OpenGL drawing code (now mostly broken out into its own module here:  https://github.com/BRL-CAD/brlcad/blob/main/src/libdm/dm-gl.c) actually pre-dates OpenGL itself in its original form.  It's still very "old school" by modern standards, and as such there's a decent chance we might be able to use tinygl to drive it as a software fallback when the system's video drivers are busted for whatever reason.

Historically we've had a raw X11 drawing backend that served that role when we have X, but that's a separate (and rather gnarly) code path to maintain which doesn't work on Windows or native OSX.  More recently I've extracted the old swrast/osmesa rendering system from Mesa to provide a stand-alone rendering system (https://github.com/BRL-CAD/brlcad/tree/main/src/other/libosmesa and https://github.com/BRL-CAD/brlcad/tree/main/src/libdm/swrast) - that works, but it's fairly slow and I'm curious if we might be able to get better performance from tinygl.  I had looked at tinygl initially, but the swrast path proved to be quicker - however, now that you've demonstrated a working tinygl on modern systems (and even basic text rendering!) it's worth another look.

The basic idea would be to do an equivalent of libdm/swrast using tinygl instead of osmesa, and then see which parts can be made to work with what tinygl provides and how it performs.

**Comment by gek169** [comment]
Thank you very much for your contribution, I accepted your PR!
Would you like to join the C-Chads as a contributor?
(I'll close this after you reply)

**Comment by gek169** [comment]
The pre-existing cmake file was contributed by Rob Loach. I don't use Cmake for any of my testing.

**Comment by starseeker** [comment]
Sure.

I'm going to make a couple more pull requests, but feel free to ignore them if they take things in a direction you prefer not to go.
